# Generated by Django 6.0 on 2025-12-23 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_sub_catagory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catagory',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='subcatagory',
            options={'ordering': ['-created_at']},
        ),
    ]
