# Generated by Django 6.0 on 2025-12-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_catagory_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagory',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
