# Generated by Django 6.0 on 2025-12-23 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_catagory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcatagory',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
