# Generated by Django 6.0 on 2025-12-29 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_product_sub_catagory_alter_product_catagory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catagory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
