# Generated by Django 5.2.4 on 2026-01-07 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_catagory_id_alter_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subcatagory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subcatagory', to='store.subcatagory'),
        ),
        migrations.AlterField(
            model_name='subcatagory',
            name='catagory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_catagorie', to='store.catagory'),
        ),
    ]
